# AutoSavePlugin Config
# time : 자동 저장 간격입니다. (초 단위)
# start-message : 저장 시작 할 때의 메세지입니다.
# end-message : 저장 끝 날 때의 메세지입니다.
# 하늘빛QP(SkyLightQP) blog.kgaons.kr

time: 60
start-message: "&6[!] &f서버 저장 중..."
end-message: "&6[!] &f서버 저장 완료!"